import { SUPABASE_MIGRATION_FILE_BY_ID } from "./supabaseMigrationCatalog.js";

export const PERSISTENCE_SCHEMA_HINTS = Object.freeze({
  businesses: {
    requiredColumns: [
      "id",
      "name",
      "website_url",
      "created_at",
    ],
  },
  website_content: {
    requiredColumns: [
      "id",
      "business_id",
      "website_url",
      "page_title",
      "meta_description",
      "content",
      "crawled_urls",
      "page_count",
      "created_at",
      "updated_at",
    ],
  },
  agents: {
    requiredColumns: [
      "id",
      "business_id",
      "client_id",
      "owner_user_id",
      "access_status",
      "public_agent_key",
      "name",
      "purpose",
      "system_prompt",
      "tone",
      "language",
      "is_active",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [SUPABASE_MIGRATION_FILE_BY_ID.owner_access],
    migrationColumns: ["owner_user_id", "access_status"],
  },
  widget_configs: {
    requiredColumns: [
      "id",
      "agent_id",
      "assistant_name",
      "welcome_message",
      "button_label",
      "primary_color",
      "secondary_color",
      "launcher_text",
      "theme_mode",
      "booking_url",
      "quote_url",
      "checkout_url",
      "booking_start_url",
      "quote_start_url",
      "booking_success_url",
      "quote_success_url",
      "checkout_success_url",
      "success_url_match_mode",
      "manual_outcome_mode",
      "contact_email",
      "contact_phone",
      "primary_cta_mode",
      "fallback_cta_mode",
      "business_hours_note",
      "install_id",
      "allowed_domains",
      "last_verification_status",
      "last_verified_at",
      "last_verification_origin",
      "last_verification_target_url",
      "last_verification_details",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [
      SUPABASE_MIGRATION_FILE_BY_ID.direct_conversion_routing,
      SUPABASE_MIGRATION_FILE_BY_ID.conversion_outcomes,
      SUPABASE_MIGRATION_FILE_BY_ID.install_verification_activation_loop,
    ],
    migrationColumns: [
      "booking_url",
      "quote_url",
      "checkout_url",
      "booking_start_url",
      "quote_start_url",
      "booking_success_url",
      "quote_success_url",
      "checkout_success_url",
      "success_url_match_mode",
      "manual_outcome_mode",
      "contact_email",
      "contact_phone",
      "primary_cta_mode",
      "fallback_cta_mode",
      "business_hours_note",
      "install_id",
      "allowed_domains",
      "last_verification_status",
      "last_verified_at",
      "last_verification_origin",
      "last_verification_target_url",
      "last_verification_details",
    ],
  },
  messages: {
    requiredColumns: [
      "id",
      "agent_id",
      "role",
      "content",
      "session_key",
      "created_at",
    ],
    migrationFiles: [SUPABASE_MIGRATION_FILE_BY_ID.messages_visitor_identity],
    migrationColumns: ["session_key"],
  },
  agent_action_queue_statuses: {
    requiredColumns: [
      "id",
      "agent_id",
      "owner_user_id",
      "action_key",
      "status",
      "note",
      "outcome",
      "next_step",
      "follow_up_needed",
      "follow_up_completed",
      "contact_status",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [SUPABASE_MIGRATION_FILE_BY_ID.action_queue_statuses],
    migrationColumns: [
      "note",
      "outcome",
      "next_step",
      "follow_up_needed",
      "follow_up_completed",
      "contact_status",
    ],
  },
  agent_follow_up_workflows: {
    requiredColumns: [
      "id",
      "agent_id",
      "owner_user_id",
      "dedupe_key",
      "source_action_key",
      "linked_action_keys",
      "action_type",
      "person_key",
      "contact_id",
      "status",
      "channel",
      "contact_name",
      "contact_email",
      "contact_phone",
      "subject",
      "draft_content",
      "last_generated_subject",
      "last_generated_content",
      "draft_edited_manually",
      "evidence",
      "why_prepared",
      "topic",
      "page_hint",
      "source_hash",
      "last_error",
      "sent_at",
      "dismissed_at",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [
      SUPABASE_MIGRATION_FILE_BY_ID.agent_follow_up_workflows,
      SUPABASE_MIGRATION_FILE_BY_ID.contacts_people_workspace,
    ],
    migrationColumns: [
      "linked_action_keys",
      "action_type",
      "person_key",
      "contact_id",
      "status",
      "channel",
      "contact_name",
      "contact_email",
      "contact_phone",
      "subject",
      "draft_content",
      "last_generated_subject",
      "last_generated_content",
      "draft_edited_manually",
      "evidence",
      "why_prepared",
      "topic",
      "page_hint",
      "source_hash",
      "last_error",
      "sent_at",
      "dismissed_at",
    ],
  },
  agent_knowledge_fix_workflows: {
    requiredColumns: [
      "id",
      "agent_id",
      "owner_user_id",
      "dedupe_key",
      "source_action_key",
      "linked_action_keys",
      "action_type",
      "status",
      "target_type",
      "target_label",
      "topic",
      "issue_key",
      "issue_summary",
      "matters_summary",
      "proposed_guidance",
      "last_generated_guidance",
      "draft_edited_manually",
      "evidence",
      "occurrence_count",
      "source_hash",
      "applied_guidance",
      "applied_at",
      "dismissed_at",
      "last_error",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [SUPABASE_MIGRATION_FILE_BY_ID.agent_knowledge_fix_workflows],
    migrationColumns: [
      "linked_action_keys",
      "action_type",
      "status",
      "target_type",
      "target_label",
      "topic",
      "issue_key",
      "issue_summary",
      "matters_summary",
      "proposed_guidance",
      "last_generated_guidance",
      "draft_edited_manually",
      "evidence",
      "occurrence_count",
      "source_hash",
      "applied_guidance",
      "applied_at",
      "dismissed_at",
      "last_error",
    ],
  },
  product_events: {
    requiredColumns: [
      "id",
      "client_id",
      "agent_id",
      "event_name",
      "source",
      "metadata",
      "created_at",
    ],
  },
  agent_installations: {
    requiredColumns: [
      "id",
      "agent_id",
      "host",
      "origin",
      "page_url",
      "last_session_id",
      "last_fingerprint",
      "first_seen_at",
      "last_seen_at",
    ],
    migrationFiles: [SUPABASE_MIGRATION_FILE_BY_ID.install_verification_activation_loop],
    migrationColumns: ["origin", "last_session_id", "last_fingerprint"],
  },
  agent_widget_events: {
    requiredColumns: [
      "id",
      "agent_id",
      "install_id",
      "session_id",
      "fingerprint",
      "event_name",
      "origin",
      "page_url",
      "metadata",
      "dedupe_key",
      "created_at",
    ],
    migrationFiles: [SUPABASE_MIGRATION_FILE_BY_ID.install_verification_activation_loop],
  },
  agent_contact_leads: {
    requiredColumns: [
      "id",
      "agent_id",
      "business_id",
      "owner_user_id",
      "install_id",
      "lead_key",
      "person_key",
      "contact_id",
      "visitor_session_key",
      "capture_state",
      "preferred_channel",
      "contact_name",
      "contact_email",
      "contact_phone",
      "contact_phone_normalized",
      "source_page_url",
      "source_origin",
      "latest_intent_type",
      "latest_action_type",
      "latest_action_key",
      "latest_message_id",
      "related_action_keys",
      "prompt_count",
      "prompted_at",
      "captured_at",
      "declined_at",
      "blocked_at",
      "first_seen_at",
      "last_seen_at",
      "capture_trigger",
      "capture_reason",
      "capture_prompt",
      "capture_source",
      "capture_metadata",
      "related_follow_up_id",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [
      SUPABASE_MIGRATION_FILE_BY_ID.live_conversion_loop,
      SUPABASE_MIGRATION_FILE_BY_ID.contacts_people_workspace,
    ],
    migrationColumns: ["contact_id"],
  },
  agent_conversion_outcomes: {
    requiredColumns: [
      "id",
      "agent_id",
      "business_id",
      "owner_user_id",
      "install_id",
      "outcome_type",
      "source_type",
      "confirmation_level",
      "dedupe_key",
      "cta_event_id",
      "related_cta_type",
      "related_target_type",
      "related_action_type",
      "related_intent_type",
      "visitor_id",
      "session_id",
      "fingerprint",
      "conversation_id",
      "person_key",
      "lead_id",
      "contact_id",
      "action_key",
      "follow_up_id",
      "page_url",
      "origin",
      "target_url",
      "success_url",
      "metadata",
      "occurred_at",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [
      SUPABASE_MIGRATION_FILE_BY_ID.conversion_outcomes,
      SUPABASE_MIGRATION_FILE_BY_ID.contacts_people_workspace,
    ],
    migrationColumns: ["contact_id"],
  },
  google_oauth_states: {
    requiredColumns: [
      "id",
      "agent_id",
      "business_id",
      "owner_user_id",
      "provider",
      "requested_scopes",
      "redirect_path",
      "selected_mailbox",
      "state_token_hash",
      "status",
      "expires_at",
      "completed_at",
      "metadata",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [SUPABASE_MIGRATION_FILE_BY_ID.connected_operator_workspace],
  },
  google_connected_accounts: {
    requiredColumns: [
      "id",
      "agent_id",
      "business_id",
      "owner_user_id",
      "provider",
      "provider_account_id",
      "account_email",
      "display_name",
      "selected_mailbox",
      "scopes",
      "scope_audit",
      "status",
      "access_token_encrypted",
      "refresh_token_encrypted",
      "token_expires_at",
      "last_refreshed_at",
      "last_sync_at",
      "last_error",
      "metadata",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [SUPABASE_MIGRATION_FILE_BY_ID.connected_operator_workspace],
  },
  operator_contacts: {
    requiredColumns: [
      "id",
      "agent_id",
      "business_id",
      "owner_user_id",
      "display_name",
      "primary_email",
      "primary_phone",
      "primary_phone_normalized",
      "primary_person_key",
      "lifecycle_state",
      "lifecycle_state_source",
      "suggested_lifecycle_state",
      "activity_sources",
      "high_priority_flags",
      "last_activity_at",
      "next_action_type",
      "next_action_title",
      "next_action_payload",
      "metadata",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [SUPABASE_MIGRATION_FILE_BY_ID.contacts_people_workspace],
  },
  operator_contact_identities: {
    requiredColumns: [
      "id",
      "contact_id",
      "agent_id",
      "business_id",
      "owner_user_id",
      "identity_type",
      "identity_value",
      "is_primary",
      "source_type",
      "first_seen_at",
      "last_seen_at",
      "metadata",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [SUPABASE_MIGRATION_FILE_BY_ID.contacts_people_workspace],
  },
  operator_inbox_threads: {
    requiredColumns: [
      "id",
      "connected_account_id",
      "agent_id",
      "business_id",
      "owner_user_id",
      "provider_thread_id",
      "provider_history_id",
      "mailbox_label",
      "subject",
      "snippet",
      "classification",
      "priority",
      "status",
      "complaint_state",
      "follow_up_state",
      "needs_reply",
      "risk_level",
      "unread_count",
      "participants",
      "contact_id",
      "related_lead_id",
      "related_follow_up_id",
      "related_action_key",
      "last_message_at",
      "metadata",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [
      SUPABASE_MIGRATION_FILE_BY_ID.connected_operator_workspace,
      SUPABASE_MIGRATION_FILE_BY_ID.contacts_people_workspace,
    ],
    migrationColumns: ["contact_id"],
  },
  operator_inbox_messages: {
    requiredColumns: [
      "id",
      "thread_id",
      "connected_account_id",
      "agent_id",
      "business_id",
      "owner_user_id",
      "provider_message_id",
      "direction",
      "approval_status",
      "message_state",
      "sender",
      "recipients",
      "cc",
      "subject",
      "body_preview",
      "body_text",
      "sent_at",
      "metadata",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [SUPABASE_MIGRATION_FILE_BY_ID.connected_operator_workspace],
  },
  operator_calendar_events: {
    requiredColumns: [
      "id",
      "connected_account_id",
      "agent_id",
      "business_id",
      "owner_user_id",
      "provider_event_id",
      "action_type",
      "source_kind",
      "status",
      "approval_status",
      "title",
      "description",
      "attendee_emails",
      "start_at",
      "end_at",
      "timezone",
      "location",
      "contact_id",
      "lead_id",
      "related_action_key",
      "conflict_state",
      "metadata",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [
      SUPABASE_MIGRATION_FILE_BY_ID.connected_operator_workspace,
      SUPABASE_MIGRATION_FILE_BY_ID.contacts_people_workspace,
    ],
    migrationColumns: ["contact_id"],
  },
  operator_campaigns: {
    requiredColumns: [
      "id",
      "agent_id",
      "business_id",
      "owner_user_id",
      "goal",
      "title",
      "status",
      "approval_status",
      "recipient_source",
      "source_filters",
      "schedule_config",
      "sequence_summary",
      "reply_handling_mode",
      "approved_at",
      "activated_at",
      "last_error",
      "metadata",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [SUPABASE_MIGRATION_FILE_BY_ID.connected_operator_workspace],
  },
  operator_campaign_steps: {
    requiredColumns: [
      "id",
      "campaign_id",
      "agent_id",
      "business_id",
      "owner_user_id",
      "step_order",
      "channel",
      "timing_offset_hours",
      "subject",
      "body",
      "approval_status",
      "metadata",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [SUPABASE_MIGRATION_FILE_BY_ID.connected_operator_workspace],
  },
  operator_campaign_recipients: {
    requiredColumns: [
      "id",
      "campaign_id",
      "agent_id",
      "business_id",
      "owner_user_id",
      "contact_id",
      "lead_id",
      "person_key",
      "contact_name",
      "contact_email",
      "status",
      "current_step_index",
      "next_send_at",
      "last_contacted_at",
      "reply_state",
      "last_thread_id",
      "metadata",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [
      SUPABASE_MIGRATION_FILE_BY_ID.connected_operator_workspace,
      SUPABASE_MIGRATION_FILE_BY_ID.contacts_people_workspace,
    ],
    migrationColumns: ["contact_id"],
  },
  operator_tasks: {
    requiredColumns: [
      "id",
      "agent_id",
      "business_id",
      "owner_user_id",
      "source_type",
      "source_id",
      "task_type",
      "title",
      "description",
      "status",
      "priority",
      "approval_required",
      "contact_id",
      "related_thread_id",
      "related_event_id",
      "related_campaign_id",
      "related_lead_id",
      "related_action_key",
      "task_state",
      "resolved_at",
      "created_at",
      "updated_at",
    ],
    migrationFiles: [
      SUPABASE_MIGRATION_FILE_BY_ID.connected_operator_workspace,
      SUPABASE_MIGRATION_FILE_BY_ID.contacts_people_workspace,
    ],
    migrationColumns: ["contact_id"],
  },
  operator_audit_logs: {
    requiredColumns: [
      "id",
      "agent_id",
      "business_id",
      "owner_user_id",
      "connected_account_id",
      "actor_type",
      "actor_id",
      "action_type",
      "target_type",
      "target_id",
      "details",
      "created_at",
    ],
    migrationFiles: [SUPABASE_MIGRATION_FILE_BY_ID.connected_operator_workspace],
  },
});

export function getPersistenceSchemaHint(tableName) {
  return PERSISTENCE_SCHEMA_HINTS[tableName] || null;
}

export function listStartupSchemaRequirements() {
  return [
    {
      table: "messages",
      columns: [
        "id",
        "agent_id",
        "role",
        "content",
        "session_key",
        "created_at",
      ],
    },
    {
      table: "widget_configs",
      columns: [
        "install_id",
        "allowed_domains",
        "last_verification_status",
        "last_verified_at",
        "last_verification_origin",
        "last_verification_target_url",
        "last_verification_details",
      ],
    },
    {
      table: "agent_installations",
      columns: ["origin", "last_session_id", "last_fingerprint"],
    },
    {
      table: "agent_widget_events",
      columns: [
        "install_id",
        "session_id",
        "fingerprint",
        "event_name",
        "origin",
        "page_url",
        "dedupe_key",
      ],
    },
    {
      table: "agent_contact_leads",
      columns: [
        "id",
        "agent_id",
        "owner_user_id",
        "install_id",
        "visitor_session_key",
        "capture_state",
        "related_action_keys",
      ],
    },
    {
      table: "agent_action_queue_statuses",
      columns: [
        "agent_id",
        "owner_user_id",
        "action_key",
        "status",
        "note",
        "outcome",
        "next_step",
        "follow_up_needed",
        "follow_up_completed",
        "contact_status",
        "updated_at",
      ],
    },
    {
      table: "agent_follow_up_workflows",
      columns: [
        "id",
        "agent_id",
        "owner_user_id",
        "dedupe_key",
        "source_action_key",
        "linked_action_keys",
        "action_type",
        "person_key",
        "status",
        "channel",
        "contact_name",
        "contact_email",
        "contact_phone",
        "subject",
        "draft_content",
        "last_generated_subject",
        "last_generated_content",
        "draft_edited_manually",
        "evidence",
        "why_prepared",
        "topic",
        "page_hint",
        "source_hash",
        "last_error",
        "sent_at",
        "dismissed_at",
        "created_at",
        "updated_at",
      ],
    },
    {
      table: "agent_knowledge_fix_workflows",
      columns: [
        "id",
        "agent_id",
        "owner_user_id",
        "dedupe_key",
        "source_action_key",
        "linked_action_keys",
        "action_type",
        "status",
        "target_type",
        "target_label",
        "topic",
        "issue_key",
        "issue_summary",
        "matters_summary",
        "proposed_guidance",
        "last_generated_guidance",
        "draft_edited_manually",
        "evidence",
        "occurrence_count",
        "source_hash",
        "applied_guidance",
        "applied_at",
        "dismissed_at",
        "last_error",
        "created_at",
        "updated_at",
      ],
    },
    {
      table: "agent_conversion_outcomes",
      columns: [
        "id",
        "agent_id",
        "owner_user_id",
        "install_id",
        "outcome_type",
        "session_id",
        "occurred_at",
      ],
    },
  ];
}
